### PR TITLE
DRAFT: Clarifying & Controlling Unwinds

### PR DESCRIPTION
**Pull request by CAD97**
To get a comment thread available for initial text review quickly

Counter-proposal to https://github.com/rust-lang/rfcs/pull/3288 (if you see the crosslink congrats you get to see this early)

Note that a number of editor comments are left in html comments

[[rich diff]](https://github.com/CAD97/rust-rfcs/pull/2/files?short_path=6a0302b#diff-6a0302b5cdff305ccbcd1dc913e96bfbb413b23adde8b377453183ad9fdc08f3) [[rendered]](https://github.com/CAD97/rust-rfcs/blob/unwinds/text/0000-clarifying-and-controlling-unwinds.md)

### CODE REVIEW

**Comment by Amanieu** [comment]
Some early notes based on a quick read:

`#[nounwind]` is generally useful and I would love to have it in the language. In fact, we *already* have this in the form of `#[rustc_allocator_nounwind]` which has exactly the semantics you want (minus using it on a `Drop` impl). It's just a matter of renaming the attribute and giving it a feature name & tracking issue.

I'm having trouble seeing the rationale for `#[catch_unwind(return)]` when you can just write the `catch_unwind` in the function body. There's no need for it to be a language-level attribute.

> When Rust's personality routine is called, it does one of two things: 

How would this work with other unwinding schemes that don't use a personality function? For example, SEH unwinding on MSVC, Emscripten unwinding, future native WASM exceptions, etc.

**Comment by CAD97** [comment]
I agree on `#[catch_unwind]`; the next revision was already going to demote it to the "maybe useful" part of the future possibilities.

I haven't looked specifically into SEH or other native unwinding mechanisms yet. The practice of maintaining a sidechannel like `panic_count` or similar is necessary to get ill-nested panics to immediately abort if the native exception runtime does not offer a way to detect this case.

For mixing foreign unwinds, noting this down now that I did a quick experiment for data:

| unwind | current | best theoretical |
| --: | :-- | :-- |
| cxx during rust | works | Itanium UB[^0] |
| rust during cxx | no panic hook, otherwise fine | abort |
| cxx catch rust | abort | mostly works (out of our control) |
| rust catch cxx | abort | “works”[^1] |
| cxx rethrow rust | works | works[^2] (out of our control) |

[^0]: Various sources, but most clearly §1.6.4 states w.r.t. C++ that behavior is undefined if a `__foreign_exception` is active at the same time as another exception. My standards brain is not strong enough to say for certain whether this (and the other statements) only mean that nesting foreign exceptions inside of a `catch` `_UA_HANDLER_FRAME` is UB and unwinding inside of cleanup frames is acceptable, or if nesting a foreign unwind during cleanup landing pads is also UB.

[^1]: Under Itanium, the unwind handler must either `_Unwind_Resume` or `_Unwind_Delete` a foreign exception (or maybe[^2] `_Unwind_RaiseException`) within the handler. Which it does must be declared in the search phase by returning `_UA_CONTINUE_UNWIND` or `_UA_HANDLER_FOUND`, respectively. Rust `catch_unwind` contains a handler, and thus must internally destroy the foreign exception. This is true even if we understand the exception object format (see §1.6.4).

[^2]: My reading of the Itanium ABI states that rethrowing a foreign exception results in undefined behavior (see §1.2, exception handler, `_URC_FOREIGN_EXCEPTION_CAUGHT`)... but then it goes on to state that rethrowing is implemented by calling `_Unwind_RaiseException` again with the same exception object (§1.3, `_Unwind_Resume`) and that a C++ `catch(...)` may rethrow a foreign exception (§1.6.4).

**Comment by CAD97** [comment]
> and that a C++ catch(...) may rethrow a foreign exception (§1.6.4)

This, at least, is resolved by §2.5.2:

> If the exception is not a C++ exception, the C++ personality routine must not catch it, that is it should return _URC_CONTINUE_UNWIND in both phases, after performing any required cleanup actions in the second phase.

C++ catching a foreign exception will call `_Unwind_Resume` on the foreign unwind. UB results if a `catch (...)` or `catch (__foreign_exception const&)` does not use `throw;` to rethrow when a foreign exception is caught.

-----

> rethrowing is implemented by calling `_Unwind_RaiseException` again with the same exception object (§1.3, `_Unwind_Resume`)

This only states how rethrowing from a handler is done on the base ABI. Combined with §2.5.4, we can presume that `__cxa_rethrow()` and `__cxa_end_catch()` collaborate to reraise and suspend the exception such that it can be passed to `_Unwind_Resume` (iff the exception is not foreign).

**Comment by CAD97** [comment]
One last note for myself: per my reading just now, I think §2.5.5 Finishing and Destroying the Exception 

> An exception is considered handled:
> - Immediately after initializing the parameter of the corresponding catch clause (or upon entry to a `catch(...)` clause).

means that for a native C++ exception, the exception is no longer active at the base ABI level during execution of the `catch` clause.

This would mean that a Rust exception during a C++ `catch` of a C++ exception is always defined behavior.

**Comment by Amanieu** [comment]
> I haven't looked specifically into SEH or other native unwinding mechanisms yet.

SEH is implemented on top of MSVC C++ exceptions. A Rust panic is just a C++ exception of type `rust_panic`. A similar thing is done for emscripten exceptions.

> For mixing foreign unwinds, noting this down now that I did a quick experiment for data:

We could make most of these work by changing `__rust_drop_panic` and `__rust_foreign_exception` to not abort. The decision to make these abort was a choice, which can be reversed to make them work as expected. This would allow C++ to catch Rust panics and discard them (instead of rethrowing them) and for Rust to catch foreign exceptions (as a `Box<ForeignException>` where `ForeignException` is a ZST: we can't support capturing & rethrowing C++ exceptions due to the way `catch_unwind` is designed).

Once those are fixed, there is only one place where an abort can occur: the C++ runtime keeps a linked list of exceptions, but `_Unwind_Exception` doesn't have a link pointer, only `__cxa_exception` does (it contains a `_Unwind_Exception`). If a `catch (...)` catches a foreign exception (Rust panic) while a C++ exception is already active (it has been thrown but not caught yet) then the runtime can't add the foreign exception to the linked list because it has no `nextException` pointer. At this point it just aborts by calling `std::terminate`.

**Comment by CAD97** [comment]
After doing the research and writing that went into this draft, I am much less confident that we should retain support for unwinds from drops. As such, I'm completely restructuring this into https://github.com/CAD97/rust-rfcs/pull/3 which puts drop-panics-unwind and drop-panics-abort on equal footing.

I respect the choice of RFC 3288 to defer any changes to nested unwinds or foreign unwinds, but believe that the picture cannot be fully contextualized without their context. This is why I continue to author a counter-RFC to present a fuller illustration of the problem space.

**Pull request closed without merging**
